### ISSUE TITLE
Division by Zero in Segment Partitioner

### ISSUE THREAD

**Issue by agavra** [responsivedev/responsive-pub#183]
It's possible that the segment interval rounds down to zero if the number of segments is larger than the retention period:
```java
  public static long computeSegmentInterval(final long retentionPeriod, final long numSegments) {
    return retentionPeriod / numSegments;
  }
```

This in turn causes the segment ID to error with division by zero:
```
  private int segmentId(final long windowTimestamp) {
    return Integer.max(0, (int) (windowTimestamp / segmentIntervalMs));
  }
```

**Comment by ableegoldman** [comment]
Fixed by https://github.com/responsivedev/responsive-pub/pull/185
