### ISSUE TITLE
Pen Test: Docker container patch management

### ISSUE THREAD

**Issue by apurvam** [responsivedev/responsive-pub#195]

**Comment by rodesai** [comment]
#203 bumps the debian version to 12 and removes wget from the final image, which should address the vulnerabilities identified.

**Comment by rodesai** [comment]
We've bumped the image to 12.4, which should address almost all vulnerabilities. The only remaining non-low-risk one is:
https://security.snyk.io/vuln/SNYK-DEBIAN12-ZLIB-6008963

There is no patched version of zlib available, and we cannot uninstall zlib. We don't use MiniZip for anything, so we should not be at risk for this CVE.
